# Generated by Django 4.2.5 on 2023-09-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_breakfast_dinner_delete_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunch',
            name='food_items',
        ),
        migrations.AddField(
            model_name='lunch',
            name='name',
            field=models.CharField(default='Default Lunch Name', max_length=255),
        ),
    ]
