# Generated by Django 4.2.5 on 2023-10-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_userprofile_height_alter_userprofile_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='calories',
            field=models.FloatField(default='100'),
        ),
        migrations.AddField(
            model_name='dinner',
            name='calories',
            field=models.FloatField(default='100'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='calories',
            field=models.FloatField(default='100'),
        ),
    ]
