# Generated by Django 4.2.5 on 2023-10-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_breakfast_calories_dinner_calories_lunch_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
